version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
        depends_on:
            - database
        entrypoint: dockerize -wait tcp://database:3306 -timeout 20s docker-entrypoint.sh
        command: node index.js

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - nodeserver

    database:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=maindb
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql

volumes: 
    mysql:
