version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
        depends_on:
            - database
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - database
    database:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=maindb
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
volumes: 
    mysql: